# Generated by Django 2.2rc1 on 2019-04-01 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_auto_20190401_1228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='user',
        ),
        migrations.AddField(
            model_name='activity',
            name='participants',
            field=models.ManyToManyField(to='tracking.Student'),
        ),
        migrations.AddField(
            model_name='activity',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='tracking.Project'),
            preserve_default=False,
        ),
    ]
