# Generated by Django 2.2rc1 on 2019-04-02 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0004_auto_20190401_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='faculties',
            field=models.ManyToManyField(related_name='courses', to='tracking.Faculty'),
        ),
        migrations.AlterField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(related_name='courses', to='tracking.Student'),
        ),
    ]
